# Generated by Django 4.1 on 2024-05-20 08:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='coin_images')),
                ('contract_add', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers', models.IntegerField()),
                ('integrity_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='coin_images')),
                ('description', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('airdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airdrop')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('tracked_airdrops', models.ManyToManyField(to='core.airdrop')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('airdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airdrop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scopeuser')),
            ],
        ),
        migrations.CreateModel(
            name='FollowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_url', models.CharField(max_length=255)),
                ('follower_num', models.IntegerField()),
                ('followed_airdrop', models.ManyToManyField(to='core.airdrop')),
            ],
        ),
        migrations.AddField(
            model_name='airdrop',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blockchain'),
        ),
    ]
