# Generated by Django 4.1 on 2024-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdrop',
            name='symbol',
            field=models.CharField(default='', max_length=25),
        ),
    ]
