# Generated by Django 4.1 on 2024-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airdrop_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airdrop',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='blockchain',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.AddField(
            model_name='airdrop',
            name='difficulty',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='airdrop',
            name='legibility',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='integrity_score',
            field=models.FloatField(),
        ),
    ]
