# Generated by Django 4.1 on 2024-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_symbol_airdrop_ticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdrop',
            name='startprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
