# Generated by Django 4.1 on 2024-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_airdrop_startprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdrop',
            name='slug',
            field=models.SlugField(blank=True, default=1721394715, null=True, unique=True),
        ),
    ]
