# Generated by Django 4.1 on 2024-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_airdrop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdrop',
            name='slug',
            field=models.SlugField(blank=True, default=1721395007, null=True),
        ),
    ]
