# Generated by Django 4.1 on 2024-07-19 13:20

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Airdrop = apps.get_model('core', 'Airdrop')
    for airdrop in Airdrop.objects.all():
        if not airdrop.slug:
            base_slug = slugify(airdrop.name)
            slug = base_slug
            counter = 1
            while Airdrop.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            airdrop.slug = slug
            airdrop.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_airdrop_slug'),  # replace with the name of your last migration
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]


