# Generated by Django 4.1 on 2024-07-19 13:44

from django.db import migrations
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Airdrop = apps.get_model('core', 'Airdrop')
    for airdrop in Airdrop.objects.all():
        base_slug = slugify(airdrop.name)  # Assuming there's a 'name' field
        slug = base_slug
        n = 1
        while Airdrop.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{n}"
            n += 1
        airdrop.slug = slug
        airdrop.save()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_populate_airdrop_slugs'),
    ]

  

    operations = [
        migrations.RunPython(generate_unique_slugs),
    ]

